dist: trusty
sudo: false
language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
addons:
  apt:
    packages:
    - libenchant-dev
    - aspell-en
cache:
  directories:
  - $HOME/.cache/pip
before_install:
- no_pylint=true
- \[ "$TRAVIS_PYTHON_VERSION" = 3.2 ] ||
  [[ "$TRAVIS_PYTHON_VERSION" =~ dev ]] ||
  no_pylint=false
install:
- \[ "$TRAVIS_PYTHON_VERSION" != "3.2" ] || pyenchant_suffix===1.6.8
- pip install pyenchant${pyenchant_suffix}
- pip install regex
- pip install pydiatra pyflakes
- $no_pylint || pip install pylint
- pip install docutils
script:
- ./mwic --version
- ./mwic --debug-dict --lang en-US
- ./mwic --debug-dict --lang en-GB
- tests/run-tests --verbose
- python3 -m pydiatra .
- python3 -m pyflakes .
- $no_pylint || private/run-pylint
- private/check-rst
- make -C doc
- make install PREFIX=~/.local
- mwic --help
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 mwic | grep -A 10 -w MWIC

# vim:ts=2 sts=2 sw=2 et
