dist: trusty
sudo: false
language: python
python:
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
addons:
  apt:
    packages:
    - libenchant-dev
    - aspell-en
cache: pip
before_install:
- if [[ $TRAVIS_PYTHON_VERSION =~ dev ]]; then if_pylint=:; fi
install:
- pip install pyenchant
- pip install regex
- pip install pydiatra pyflakes
- $if_pylint pip install pylint
- pip install docutils
script:
- ./mwic --version
- ./mwic --debug-dict --lang en-US
- ./mwic --debug-dict --lang en-GB
- tests/run-tests --verbose
- python3 -m pydiatra .
- python3 -m pyflakes .
- $if_pylint  private/run-pylint
- private/check-rst
- make -C doc
- make install PREFIX=~/.local
- cd /
- mwic --help
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 mwic | grep -A 10 -w MWIC

# vim:ts=2 sts=2 sw=2 et
